# Generated by Django 4.2.9 on 2024-07-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('desktops', 'desktops'), ('laptops', 'laptops'), ('extensions', 'extensions'), ('screens', 'screens'), ('banners', 'banners')], max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
